### ISSUE TITLE
Building Upgrades / Building buildings

### ISSUE THREAD

**Issue by zulater** [LorgeN/CrazyWars-Issues#53]
**Is your feature request related to a problem? Please describe.**
No major problem, slight annoyance.  

**Describe the solution you'd like**
Since the max amount of upgrades you can do now is hooked to your island skills and limited to 5 it would be nice if you could queue more.  So only 5 buildings could be upgraded at a single time but you could queue 50 and so when the first 5 got done it would go to the next 5 etc.  You pay all of it up front

**Describe alternatives you've considered**
Current setup or allow for more buildings to be upgraded based on the ability to use more skill points (increase max of 5 to some higher number)

**Comment by LorgeN** [comment]
Could look into this at some point, but it's a lot of work. 

Mostly because of how complex the mathematics will be, having to interact with the other buildings, calculating exactly when they complete and starting the queued building at that point (without actually starting it at that time, this is all handled when an island loads).

**Comment by LorgeN** [comment]
Increased the max amount of buildings you can build at any time.
