### ISSUE TITLE
Buildings with fuel as full still accepting duel

### ISSUE THREAD

**Issue by kokoPvP** [LorgeN/CrazyWars-Issues#64]
**Minecraft Username**
kokoPvP (found by ArceusFoxx)

**What is this about?**
When a building is full sometimes it with still accept fuel.

**To Reproduce**
A. Fill the building fully.
B. Put more fuel in the building.

**What happens?**
It takes more fuel then it should and wastes your fuel.

**What should happen?**
It should deny any extra fuel.

**Screenshots/Videos**
https://www.youtube.com/watch?v=57pivoczA3g&feature=youtu.be (this proof is provided by ArceusFoxx)

**Comment by wzhouruize** [comment]
This is because the holy torch uses fuel constantly instead of per use like a block grinder, so right after you click it is already consuming fuel, and thus accepts a new lava bucket. If you tried shift clicking with a stackable item like coal, it will stop once it is full but continue to accept new fuel.
